### ISSUE TITLE
Fractional seconds

### ISSUE THREAD

**Issue by ldgrp** [Guthers/snails#17]
The current database model does not support fractional seconds.

Here are some relevant links

https://docs.sqlalchemy.org/en/13/dialects/mysql.html#sqlalchemy.dialects.mysql.DATETIME
https://dev.mysql.com/doc/refman/8.0/en/fractional-seconds.html

**Comment by Joshua-Hwang** [comment]
With ~not~ very thorough testing
0dabcd14b3c8d690a487a67b257a08a886806450
